// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flfcqbomwmbpuxdhpfwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZmNxYm9td21icHV4ZGhwZndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTQ1NzUsImV4cCI6MjA1ODgzMDU3NX0.lsImCN19PXNXBTm2B7qDXdr6YMgJ7deKOefAsW9-OF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);